
development:
  adapter: postgresql
  encoding: unicode
  database: store

production:
  adapter: postgresql
  encoding: unicode
  user: store
  database: store_production
  password: <%= ENV['STORE_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
